name: tree_structures
description: tree_structures is a Dart implentation of (currently only) a red-black self-balancing binary search tree with a possibility to output to Graphviz for previewing.
version: 0.0.2
repository: https://github.com/iuthere/tree_structures

environment:
  sdk: ">=2.13.0 <3.0.0"

dev_dependencies:
  test: ^1.17.10
